import os
import httpx
from abc import ABC, abstractmethod


class LLMClient(ABC):
    """
    Abstract LLM client interface.
    """

    @abstractmethod
    def generate(self, prompt: str) -> str:
        raise NotImplementedError


class DummyLLMClient(LLMClient):
    """
    Dummy LLM for testing.
    """

    def generate(self, prompt: str) -> str:
        return "Summary generated by Dummy LLM."


class OllamaCloudClient(LLMClient):
    """
    Cloud-based Ollama LLM client.
    """

    def __init__(
        self,
        model: str,
        api_key: str | None = None,
        base_url: str = "https://ollama.com/api/chat",
        timeout: int = 60,
    ):
        self.model = model
        self.api_key = api_key or os.getenv("OLLAMA_API_KEY")
        self.base_url = base_url
        self.timeout = timeout

        if not self.api_key:
            raise ValueError("OLLAMA_API_KEY is not set")

    def generate(self, prompt: str) -> str:
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        payload = {
            "model": self.model,
            "messages": [{"role": "user", "content": prompt}],
            "stream": False,
        }

        with httpx.Client(timeout=self.timeout) as client:
            response = client.post(
                self.base_url,
                headers=headers,
                json=payload,
            )

            response.raise_for_status()
            data = response.json()

        return data["message"]["content"]
